# coding: utf-8

"""
    Push Notification Service API

           Enterprise-grade Push Notification Service supporting iOS, Android, and Web platforms.              ## Features       - 🚀 Multi-platform push notifications (FCM, APNs, Web Push)       - 📱 Advanced device management and segmentation       - 📊 Real-time analytics and delivery tracking       - 🏷️ Template-based notifications with variable substitution       - ⚡ High-performance queue system with BullMQ       - 🔒 Enterprise security with API key authentication       - 🛡️ Rate limiting for API protection       - 📈 99.9% uptime reliability target              ## Authentication       All endpoints require an API key in the `X-API-Key` header.              ## Rate Limiting       API endpoints are rate-limited to ensure fair usage:       - **High Frequency**: 100 requests/minute (notifications, events)       - **Medium Frequency**: 300 requests/minute (device management)       - **Low Frequency**: 1000 requests/hour (analytics, admin)              Rate limit headers are included in all responses:       - `X-RateLimit-Limit`: Maximum requests allowed       - `X-RateLimit-Remaining`: Requests remaining in current window       - `X-RateLimit-Reset`: Unix timestamp when the rate limit resets     

    The version of the OpenAPI document: 1.0.0
    Contact: support@yourcompany.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.validate_template_dto import ValidateTemplateDto

class TestValidateTemplateDto(unittest.TestCase):
    """ValidateTemplateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateTemplateDto:
        """Test ValidateTemplateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateTemplateDto`
        """
        model = ValidateTemplateDto()
        if include_optional:
            return ValidateTemplateDto(
                title = '',
                body = '',
                image_url = '',
                data = None,
                test_variables = {"userName":"John Doe","action":"test_action"}
            )
        else:
            return ValidateTemplateDto(
                title = '',
                body = '',
                test_variables = {"userName":"John Doe","action":"test_action"},
        )
        """

    def testValidateTemplateDto(self):
        """Test ValidateTemplateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
