# coding: utf-8

# flake8: noqa

"""
    Push Notification Service API

           Enterprise-grade Push Notification Service supporting iOS, Android, and Web platforms.              ## Features       - 🚀 Multi-platform push notifications (FCM, APNs, Web Push)       - 📱 Advanced device management and segmentation       - 📊 Real-time analytics and delivery tracking       - 🏷️ Template-based notifications with variable substitution       - ⚡ High-performance queue system with BullMQ       - 🔒 Enterprise security with API key authentication       - 🛡️ Rate limiting for API protection       - 📈 99.9% uptime reliability target              ## Authentication       All endpoints require an API key in the `X-API-Key` header.              ## Rate Limiting       API endpoints are rate-limited to ensure fair usage:       - **High Frequency**: 100 requests/minute (notifications, events)       - **Medium Frequency**: 300 requests/minute (device management)       - **Low Frequency**: 1000 requests/hour (analytics, admin)              Rate limit headers are included in all responses:       - `X-RateLimit-Limit`: Maximum requests allowed       - `X-RateLimit-Remaining`: Requests remaining in current window       - `X-RateLimit-Reset`: Unix timestamp when the rate limit resets     

    The version of the OpenAPI document: 1.0.0
    Contact: support@yourcompany.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AnalyticsApi",
    "AppApi",
    "DevicesApi",
    "HealthApi",
    "NotificationsApi",
    "ProjectsApi",
    "QueuesApi",
    "RateLimitAdminApi",
    "TemplatesApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateTemplateDto",
    "ErrorResponseDto",
    "NotificationsList200Response",
    "RenderTemplateDto",
    "UpdateTemplateDto",
    "ValidateTemplateDto",
]

# import apis into sdk package
from openapi_client.api.analytics_api import AnalyticsApi as AnalyticsApi
from openapi_client.api.app_api import AppApi as AppApi
from openapi_client.api.devices_api import DevicesApi as DevicesApi
from openapi_client.api.health_api import HealthApi as HealthApi
from openapi_client.api.notifications_api import NotificationsApi as NotificationsApi
from openapi_client.api.projects_api import ProjectsApi as ProjectsApi
from openapi_client.api.queues_api import QueuesApi as QueuesApi
from openapi_client.api.rate_limit_admin_api import RateLimitAdminApi as RateLimitAdminApi
from openapi_client.api.templates_api import TemplatesApi as TemplatesApi
from openapi_client.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.create_template_dto import CreateTemplateDto as CreateTemplateDto
from openapi_client.models.error_response_dto import ErrorResponseDto as ErrorResponseDto
from openapi_client.models.notifications_list200_response import NotificationsList200Response as NotificationsList200Response
from openapi_client.models.render_template_dto import RenderTemplateDto as RenderTemplateDto
from openapi_client.models.update_template_dto import UpdateTemplateDto as UpdateTemplateDto
from openapi_client.models.validate_template_dto import ValidateTemplateDto as ValidateTemplateDto

