# coding: utf-8

"""
    Push Notification Service API

           Enterprise-grade Push Notification Service supporting iOS, Android, and Web platforms.              ## Features       - 🚀 Multi-platform push notifications (FCM, APNs, Web Push)       - 📱 Advanced device management and segmentation       - 📊 Real-time analytics and delivery tracking       - 🏷️ Template-based notifications with variable substitution       - ⚡ High-performance queue system with BullMQ       - 🔒 Enterprise security with API key authentication       - 🛡️ Rate limiting for API protection       - 📈 99.9% uptime reliability target              ## Authentication       All endpoints require an API key in the `X-API-Key` header.              ## Rate Limiting       API endpoints are rate-limited to ensure fair usage:       - **High Frequency**: 100 requests/minute (notifications, events)       - **Medium Frequency**: 300 requests/minute (device management)       - **Low Frequency**: 1000 requests/hour (analytics, admin)              Rate limit headers are included in all responses:       - `X-RateLimit-Limit`: Maximum requests allowed       - `X-RateLimit-Remaining`: Requests remaining in current window       - `X-RateLimit-Reset`: Unix timestamp when the rate limit resets     

    The version of the OpenAPI document: 1.0.0
    Contact: support@yourcompany.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateTemplateDto(BaseModel):
    """
    CreateTemplateDto
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=100)] = Field(description="Template name")
    description: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="Template description")
    title: Annotated[str, Field(strict=True, max_length=200)] = Field(description="Notification title template")
    body: Annotated[str, Field(strict=True, max_length=1000)] = Field(description="Notification body template")
    image_url: Optional[StrictStr] = Field(default=None, description="Image URL template", alias="imageUrl")
    data: Optional[Dict[str, Any]] = Field(default=None, description="Custom data template")
    variables: Optional[List[StrictStr]] = Field(default=None, description="Template variables")
    status: Optional[StrictStr] = Field(default=None, description="Template status")
    default_values: Optional[Dict[str, Any]] = Field(default=None, description="Default variable values", alias="defaultValues")
    language: Optional[StrictStr] = Field(default=None, description="Template language")
    validation_rules: Optional[Dict[str, Any]] = Field(default=None, description="Validation rules for variables", alias="validationRules")
    version: Optional[Union[StrictFloat, StrictInt]] = Field(default=1, description="Template version")
    created_by: Optional[StrictStr] = Field(default=None, description="Created by user ID", alias="createdBy")
    __properties: ClassVar[List[str]] = ["name", "description", "title", "body", "imageUrl", "data", "variables", "status", "defaultValues", "language", "validationRules", "version", "createdBy"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'inactive']):
            raise ValueError("must be one of enum values ('active', 'inactive')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateTemplateDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateTemplateDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "title": obj.get("title"),
            "body": obj.get("body"),
            "imageUrl": obj.get("imageUrl"),
            "data": obj.get("data"),
            "variables": obj.get("variables"),
            "status": obj.get("status"),
            "defaultValues": obj.get("defaultValues"),
            "language": obj.get("language"),
            "validationRules": obj.get("validationRules"),
            "version": obj.get("version") if obj.get("version") is not None else 1,
            "createdBy": obj.get("createdBy")
        })
        return _obj


